
import 'dart:convert';

import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';
import 'package:newpaper_app/homescreen/model/hoemodel.dart';

class Homeprovider extends ChangeNotifier
{
  Map<dynamic,dynamic> newsJsonMapList = {};

  List<Articles> newsJsonList = [];

  Future<void> jsonParshingOfNewsdata()
  async {
    String newsDataJsonInString = await rootBundle.loadString("assets/json/news.json");
    var newsDataInJson = jsonDecode(newsDataJsonInString);
    var articleList = newsDataInJson['articles'] as List;
    newsJsonList = articleList.map((e)=>Articles().jsonDataFromArticles(e)).toList();
    newsJsonMapList = newsDataInJson;
    notifyListeners();
  }

  List newsCompanyNameList = [
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",
    "Forbes",
    "New York Times",
    "Times Of India",
    "Aaj Tak",
    "Divya Bhaskar",
    "India TV",

  ];
  
  List newsCompanyImgList = [
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
    "assets/tik/tom.png",
    "assets/tik/aaj.jpg",
    "assets/tik/div.png",
    "assets/tik/ind.jpg",
    "assets/tik/forb.webp",
    "assets/tik/us.jpg",
  ];



}